### PR TITLE
refactor(worker): proposal/ideas 

### PR DESCRIPTION
**Pull request by jvancoillie**
| Q                | A
| ---------------- | ---
| PHP version?     | 7.4
| Bundle version?  | 0.4.4
| New feature?     | no
| Bug fix?         | no
| Discussion?      | #92, #77, #102

I modified the execution method a bit. It's far from perfect, but it's easier for me than trying to present my ideas in English.
* remove shouldStop while loop
* add method for processing tasks 

This modification has the advantage of not dispatching the `WorkerStartedEvent` on each recursion.

I also isolated the process of running tasks, it could be useful to launch chained tasks more simply (I saw that you had started working on it #103)

```php
    public function run(TaskInterface $task, WorkerInterface $worker): Output
    {
        if (!$task instanceof ChainedTask) {
            $task->setExecutionState(TaskInterface::ERRORED);
            return new Output($task, null, Output::ERROR);
        }

        try {
            $worker->processTasks($task->getTasks());
        } catch (Throwable $throwable) {
            $task->setExecutionState(TaskInterface::ERRORED);
            return new Output($task, $throwable->getMessage(), Output::ERROR);
        }

        $task->setExecutionState(TaskInterface::SUCCEED);
        return new Output($task, null, Output::SUCCESS);
    }
```
I wondered about the interest of this while loop.

https://github.com/Guikingone/SchedulerBundle/blob/6eb5077d046b3051e82e488fe8e95185fcc629af/src/Worker/Worker.php#L102

I think it was useful only with the `--wait` option and does not add anything to a simple `consume`. 

These modifications are not satisfactory but I think that it allows to expose my visions to you and thus to exchange more easily

### CODE REVIEW

**Comment by jvancoillie** [comment]
Hello @Guikingone 👋 

I think this proposal can be closed as you have worked on it. 
Maybe changing the `while` loop is still interesting because for me there is no need to loop over it except with the `--wait` option

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

It depends, I haven't read this PR to be honest 😅 

There's might be some interesting ideas, could you rebase it against `main` and see if it work? 

This way, the review will be easier 🙂

**Comment by jvancoillie** [comment]
> Hi @jvancoillie 👋🏻
> 
> It depends, I haven't read this PR to be honest 😅

 😭 

> There's might be some interesting ideas, could you rebase it against `main` and see if it work?
> 
> This way, the review will be easier 🙂

I can try to do that, I'm afraid that there is too much difference for it to be easy to `rebase` and in the end maybe not much of interest. I test and I tell you what it is

**Comment by Guikingone** [comment]
> 😭

Sorry to be honest 😅 

No problem for the rebase, I'm gonna read this PR tonight and see if something can be saved/used for an improvement 🙂

**Comment by jvancoillie** [comment]
> Sorry to be honest 😅

it's very good I prefer honest people

> No problem for the rebase, I'm gonna read this PR tonight and see if something can be saved/used for an improvement 🙂

don't bother to review this PR.

The modification mainly focused on a method of performing tasks as you may have made with the `AbstactWorker::run`.

The only little thing I see is on the callback function passed to the `run` method. It's not much I could always suggest a new PR or open a discussion for it.

**Comment by jvancoillie** [comment]
is no longer relevant following recent refactoring

**Pull request closed without merging**
