### PR TITLE
refactor(scheduler): float check improved

### PR DESCRIPTION
**Pull request by Guikingone**
| Q                | A
| ---------------- | ---
| PHP version?     | 8.0
| Bundle version?  | 0.8.1
| Symfony version? | >= 5.4
| New feature?     | no
| Bug fix?         | yes
| Discussion?      | #216

### CODE REVIEW

**Comment by Guikingone** [comment]
Hi @xaviermarchegay 👋🏻 

Sorry for the delay, when you have a moment, could you try if the error continues to be raised using `dev-issue/217` branch? 

Thanks 🙂

**Comment by xaviermarchegay** [comment]
Thks @Guikingone I just installed it on my project. It is a rare bug (once every day?) so I am not sure that I can be sure that the fix works.

I will tell you by the end of the week if it happened again.

**Comment by xaviermarchegay** [comment]
Sorry, the anomaly is still happening the same way.

**Comment by Guikingone** [comment]
Hi @xaviermarchegay, 

No issue here, I wasn't expecting to work perfectly from the first shot 😅 

I'm gonna investigate it 🙂

**Comment by Guikingone** [comment]
Hi @xaviermarchegay 👋🏻 

I've pushed a new fix for this issue, could you see if it fix your local problem?

It was related to the sync usage / cast if you wonder why 😅 

Thanks for the feedback 🙂

**Comment by xaviermarchegay** [comment]
@Guikingone I just installed  "dev-issue/217 ddc23be" in my composer.json

Wait and see.

**Comment by xaviermarchegay** [comment]
@Guikingone I don't reproduce the issue. I assume the fix is correct. :+1:

**Comment by Guikingone** [comment]
@xaviermarchegay Nice, love to read this 😄 

I merge the fix and release `0.8.1` today 🙂

**Pull request merged**
