### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by jmsche**
| Q                | A
| ---------------- | ---
| PHP version?     | 8.0
| Bundle version?  | 0.8.0
| Symfony version? | 6.0
| New feature?     | yes
| Bug fix?         | no
| Discussion?      | N/A

Add support for Symfony 6.
CI runs against 5.4.x-dev & 6.0.x-dev.
I don't know if it will pass :D

### CODE REVIEW

**Comment by Guikingone** [comment]
You should consider adding:

```json
"require": {
    "php": "^7.4 || ^8.0"
}
```

**Comment by jmsche** [comment]
Why? It already allows PHP 8 :)

**Comment by jmsche** [comment]
So, security fail is "normal".

Infection & Rector seem to fail, but not due to my changes.

* Security fails but that's due to snyk that does not want to run as I'm the author of the PR
* Rector fails but unrelated to my changes
* Infection fails but unrelated to my changes
* Static analysis, code style pass (still unrelated to my changes :))
* PHPUnit is okay for all runs 

PR seems good to me, tell me if I have to do something?

**Comment by Guikingone** [comment]
Hum, maybe we can remove `api-platform/core`, that's not used for now 🤔

**Comment by jmsche** [comment]
So... There's progress! :)

Unfortunately, I don't even know how the following error can happen :/ https://github.com/Guikingone/SchedulerBundle/runs/4328001061?check_suite_focus=true#step:9:40

**Comment by Guikingone** [comment]
Regarding `psalm/symfony-plugin`, it can be removed as we don't use it anymore.

**Comment by Guikingone** [comment]
Hi @jmsche 👋🏻 

Support for Sf 6 has been merged, I'm closing this issue, thanks for the help 🙂

**Pull request closed without merging**
