### PR TITLE
Fix Symfony 6.3 deprecation

### PR DESCRIPTION
**Pull request by jmsche**
| Q                | A
| ---------------- | ---
| PHP version?     | 8.2
| Bundle version?  | 0.10.2
| Symfony version? | 6.3.0
| New feature?     | no
| Bug fix?         | yes?
| Discussion?      | #315 

This PR should fix the deprecations coming with Symfony 6.3 (see #315).

### CODE REVIEW

**Comment by jmsche** [comment]
CI failures seem unrelated.

**Comment by jmsche** [comment]
I just fixed the PHPStan warnings about the code I added :)

**Comment by Guikingone** [comment]
Hi @jmsche 👋🏻 

Thanks for the PR, could you check the warnings from PHPStan?

Thanks 🙂

**Comment by jmsche** [comment]
Hi @Guikingone,

PHPStan warnings related to th PR additions have been fixed :)

**Comment by Guikingone** [comment]
Wow, that was fast 😮 

A huge thank @jmsche, should be out soon via `0.10.3`.

**Pull request merged**
